// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TransferenciasApiCore.Models.Usuario;

[Table("EscoUsuarioApp", Schema = "web")]
public partial class EscoUsuarioApp
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("codigo", TypeName = "character varying")]
    public string Codigo { get; set; }

    [Column("nombrecompleto", TypeName = "character varying")]
    public string NombreCompleto { get; set; }

    [Column("contrasena", TypeName = "character varying")]
    public string Contrasena { get; set; }

    [Column("sector_id")]
    public int? SectorId { get; set; }
}