// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace TransferenciasApiCore.Models;
public partial class EscoUsuarioAppLoginDto
{
    public string Codigo { get; set; }
    public string Contrasena { get; set; }
}