// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace TransferenciasApiCore.Models.SolicitudTransferencia;

public partial class EscoTxSolicitudTransferenciaUpdateEstadoDto
{
    public int Id { get; set; }
    public int? EstadoId { get; set; }
}