// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace TransferenciasApiCore.Models.SolicitudTransferencia;

public partial class EscoTxSolicitudTransferenciaInsertDto
{
    public int? EstadoId { get; set; }
    public int UsuarioId { get; set; }
    public List<EscoTxItemSolicitudTransferenciaInsertDto> ItemsSolicitudTransferencia { get; set; }
}