// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace TransferenciasApiCore.Models.SolicitudTransferencia;

public partial class EscoTxItemSolicitudTransferenciaUpdatePickeadoDto
{
    public int Id { get; set; }
    public bool Pickeado { get; set; }
}