// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.Text.Json.Serialization;

namespace TransferenciasApiCore.Models.SolicitudTransferencia;

public partial class EscoTxItemSolicitudTransferenciaInsertDto
{
    public Guid? ProductoId { get; set; }
    public decimal? Cantidad { get; set; }
    public Guid? UnidadMedidaId { get; set; }
    [JsonIgnore]
    public int? SolicitudTransferenciaId { get; set; }
    public int? EstadoId { get; set; }
    public bool? Pickeado { get; set; }
}