// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace TransferenciasApiCore.Models.SolicitudTransferencia;

[Table("EscoTxItemSolicitudTransferencia", Schema = "web")]
public partial class EscoTxItemSolicitudTransferencia
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("producto_id")]
    public Guid? ProductoId { get; set; }

    [Column("cantidad")]
    public decimal? Cantidad { get; set; }

    [Column("unidadmedida_id")]
    public Guid? UnidadMedidaId { get; set; }

    [Column("solicitudtransferencia_id")]
    public int? SolicitudTransferenciaId { get; set; }

    [Column("estado_id")]
    public int? EstadoId { get; set; }

    [Column("pickeado")]
    public bool Pickeado { get; set; }
}