// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TransferenciasApiCore.Models.SolicitudTransferencia;

[Table("EscoTxSolicitudTransferencia", Schema = "web")]
public partial class EscoTxSolicitudTransferencia
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("estado_id")]
    public int? EstadoId { get; set; }

    [Column("fecha", TypeName = "timestamp without time zone")]
    public DateTime? Fecha { get; set; }

    [Column("fechamodificacion", TypeName = "timestamp without time zone")]
    public DateTime? FechaModificacion { get; set; }

    [Column("usuario_id")]
    public int UsuarioId { get; set; }
    [NotMapped]
    public List<EscoTxItemSolicitudTransferencia> ItemsSolicitudTransferencia { get; set; }
}