// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TransferenciasApiCore.Models;

[Table("deposito")]
[Index("BoPlaceId", Name = "idx00344313")]
[Index("BoOwnerId", Name = "idx00344314")]
[Index("UnidadoperativaId", Name = "idx00344315")]
public partial class deposito
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("bo_place_id")]
    public Guid? BoPlaceId { get; set; }

    [Column("bo_owner_id")]
    public Guid? BoOwnerId { get; set; }

    [Column("activestatus")]
    public int? Activestatus { get; set; }

    [Column("nombre")]
    [StringLength(100)]
    public string Nombre { get; set; }

    [Column("codigo")]
    [StringLength(25)]
    public string Codigo { get; set; }

    [Column("ubicaciones_id")]
    public Guid? UbicacionesId { get; set; }

    [Column("ubicaciondefault_id")]
    public Guid? UbicaciondefaultId { get; set; }

    [Column("grupovaluacioninventario_id")]
    public Guid? GrupovaluacioninventarioId { get; set; }

    [Column("tipovaluacion_id")]
    public Guid? TipovaluacionId { get; set; }

    [Column("unidadoperativa_id")]
    public Guid? UnidadoperativaId { get; set; }

    [Column("domicilio_id")]
    public Guid? DomicilioId { get; set; }

    [Column("datoscomplementarios_id")]
    public Guid? DatoscomplementariosId { get; set; }

    [Column("valuaciones_id")]
    public Guid? ValuacionesId { get; set; }

    [Column("itemrecursouso_id")]
    public Guid? ItemrecursousoId { get; set; }

    [Column("calculointerno")]
    public bool? Calculointerno { get; set; }

    [Column("boextension_id")]
    public Guid? BoextensionId { get; set; }

    [Column("metodoextraccion_id")]
    public Guid? MetodoextraccionId { get; set; }

    [Column("metodoabastecimiento_id")]
    public Guid? MetodoabastecimientoId { get; set; }

    [Column("cuentascontables_id")]
    public Guid? CuentascontablesId { get; set; }

    [Column("bocsf_id")]
    public Guid? BocsfId { get; set; }

    [Column("usuario")]
    [StringLength(50)]
    public string Usuario { get; set; }

    [Column("tipodeposito_id")]
    public Guid? TipodepositoId { get; set; }
}