// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TransferenciasApiCore.Models;

[Table("EscoTxEtiqueta", Schema = "web")]
public partial class EscoTxEtiqueta
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("codigo", TypeName = "character varying")]
    public string Codigo { get; set; }

    [Column("producto_id")]
    public Guid? ProductoId { get; set; }

    [Column("cantidad")]
    public decimal? Cantidad { get; set; }

    [Column("fecha", TypeName = "timestamp without time zone")]
    public DateTime? Fecha { get; set; }

    [Column("estado_id")]
    public int? EstadoId { get; set; }
}