// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TransferenciasApiCore.Models;

[Table("EscoTxEstado", Schema = "web")]
public partial class EscoTxEstado
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("codigo", TypeName = "character varying")]
    public string Codigo { get; set; }

    [Column("descripcion", TypeName = "character varying")]
    public string Descripcion { get; set; }
}