// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TransferenciasApiCore.Models;

[Table("iteminventario")]
[Index("BoPlaceId", Name = "idx00344301")]
[Index("ProductoId", Name = "idx00344302")]
[Index("SerieId", Name = "idx00344303")]
[Index("LoteId", Name = "idx00344304")]
[Index("DespachoId", Name = "idx00344305")]
[Index("EnvaseId", Name = "idx00344306")]
[Index("DepositoId", Name = "idx00344307")]
[Index("UbicacionId", Name = "idx00344308")]
[Index("ProductoId", "Fechacreacion", Name = "idx00344309")]
[Index("ProductoId", "BoPlaceId", Name = "idx00344310")]
public partial class iteminventario
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("bo_place_id")]
    public Guid? BoPlaceId { get; set; }

    [Column("bo_owner_id")]
    public Guid? BoOwnerId { get; set; }

    [Column("producto_id")]
    public Guid? ProductoId { get; set; }

    [Column("descripcion")]
    [StringLength(100)]
    public string Descripcion { get; set; }

    [Column("cantidad_id")]
    public Guid? CantidadId { get; set; }

    [Column("cantidad2_cantidad")]
    [Precision(22, 10)]
    public decimal? Cantidad2Cantidad { get; set; }

    [Column("cantidad2_unidadmedida_id")]
    public Guid? Cantidad2UnidadmedidaId { get; set; }

    [Column("costo_id")]
    public Guid? CostoId { get; set; }

    [Column("costo2_importe")]
    [Precision(22, 10)]
    public decimal? Costo2Importe { get; set; }

    [Column("costo2_unidadvalorizacion_id")]
    public Guid? Costo2UnidadvalorizacionId { get; set; }

    [Column("costo2_momento")]
    [StringLength(17)]
    public string Costo2Momento { get; set; }

    [Column("costo2_nombre")]
    [StringLength(30)]
    public string Costo2Nombre { get; set; }

    [Column("serie_id")]
    public Guid? SerieId { get; set; }

    [Column("lote_id")]
    public Guid? LoteId { get; set; }

    [Column("despacho_id")]
    public Guid? DespachoId { get; set; }

    [Column("envase_id")]
    public Guid? EnvaseId { get; set; }

    [Column("bultos")]
    public int? Bultos { get; set; }

    [Column("cantidadnolineal_id")]
    public Guid? CantidadnolinealId { get; set; }

    [Column("cnolineal2_cantidad")]
    [Precision(22, 10)]
    public decimal? Cnolineal2Cantidad { get; set; }

    [Column("cnolineal2_unidadmedida_id")]
    public Guid? Cnolineal2UnidadmedidaId { get; set; }

    [Column("fechainv")]
    [StringLength(14)]
    public string Fechainv { get; set; }

    [Column("fechaven")]
    [StringLength(14)]
    public string Fechaven { get; set; }

    [Column("imputacioncontable_id")]
    public Guid? ImputacioncontableId { get; set; }

    [Column("deposito_id")]
    public Guid? DepositoId { get; set; }

    [Column("ubicacion_id")]
    public Guid? UbicacionId { get; set; }

    [Column("peso")]
    [Precision(22, 10)]
    public decimal? Peso { get; set; }

    [Column("volumen")]
    [Precision(22, 10)]
    public decimal? Volumen { get; set; }

    [Column("fechaactualizacion")]
    [StringLength(17)]
    public string Fechaactualizacion { get; set; }

    [Column("itemrecursoconsumo_id")]
    public Guid? ItemrecursoconsumoId { get; set; }

    [Column("lockstatusinv")]
    public bool? Lockstatusinv { get; set; }

    [Column("fechacreacion")]
    [StringLength(17)]
    public string Fechacreacion { get; set; }

    [Column("costori_importe")]
    [Precision(22, 10)]
    public decimal? CostoriImporte { get; set; }

    [Column("costori_unidadvalorizacion_id")]
    public Guid? CostoriUnidadvalorizacionId { get; set; }

    [Column("costori_momento")]
    [StringLength(17)]
    public string CostoriMomento { get; set; }

    [Column("costori_nombre")]
    [StringLength(30)]
    public string CostoriNombre { get; set; }

    [Column("propietario_id")]
    public Guid? PropietarioId { get; set; }

    [Column("boextension_id")]
    public Guid? BoextensionId { get; set; }

    [Column("datoscomplementarios_id")]
    public Guid? DatoscomplementariosId { get; set; }

    [Column("objetoasociado_id")]
    public Guid? ObjetoasociadoId { get; set; }

    [Column("agrupacioninventario_id")]
    public Guid? AgrupacioninventarioId { get; set; }

    [Column("dimensionalidad_id")]
    public Guid? DimensionalidadId { get; set; }

    [Column("esquemaoperativo_id")]
    public Guid? EsquemaoperativoId { get; set; }

    [Column("proyecto_id")]
    public Guid? ProyectoId { get; set; }
}