// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TransferenciasApiCore.Models;

[Table("producto")]
[Index("BoPlaceId", Name = "idx00344081")]
[Index("Codigo", Name = "idx00344082")]
[Index("RubroId", Name = "idx00344083")]
public partial class producto
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("activestatus")]
    public int? Activestatus { get; set; }

    [Column("checksoptimisticupdates")]
    [StringLength(40)]
    public string Checksoptimisticupdates { get; set; }

    [Column("codigo")]
    [StringLength(30)]
    public string Codigo { get; set; }

    [Column("segmento_id")]
    public Guid? SegmentoId { get; set; }

    [Column("descripcion")]
    [StringLength(150)]
    public string Descripcion { get; set; }

    [Column("usuario")]
    [StringLength(30)]
    public string Usuario { get; set; }

    [Column("momento")]
    [StringLength(17)]
    public string Momento { get; set; }

    [Column("catalogo_id")]
    public Guid? CatalogoId { get; set; }

    [Column("itemcatalogo_id")]
    public Guid? ItemcatalogoId { get; set; }

    [Column("codigosalternativos_id")]
    public Guid? CodigosalternativosId { get; set; }

    [Column("detalleproveedores_id")]
    public Guid? DetalleproveedoresId { get; set; }

    [Column("listacosto_id")]
    public Guid? ListacostoId { get; set; }

    [Column("grupocomposicion_id")]
    public Guid? GrupocomposicionId { get; set; }

    [Column("rubro_id")]
    public Guid? RubroId { get; set; }

    [Column("posicionadorimpuestos_id")]
    public Guid? PosicionadorimpuestosId { get; set; }

    [Column("partidapresup_id")]
    public Guid? PartidapresupId { get; set; }

    [Column("tipodistribuciondefault_id")]
    public Guid? TipodistribuciondefaultId { get; set; }

    [Column("composicion_id")]
    public Guid? ComposicionId { get; set; }

    [Column("clasificacioncosto_id")]
    public Guid? ClasificacioncostoId { get; set; }

    [Column("boextension_id")]
    public Guid? BoextensionId { get; set; }

    [Column("componentecosto_id")]
    public Guid? ComponentecostoId { get; set; }

    [Column("definicioncompcosto_id")]
    public Guid? DefinicioncompcostoId { get; set; }

    [Column("tipoobjetoestatico_id")]
    public Guid? TipoobjetoestaticoId { get; set; }

    [Column("flag_id")]
    public Guid? FlagId { get; set; }

    [Column("transicion_id")]
    public Guid? TransicionId { get; set; }

    [Column("centrocostos_id")]
    public Guid? CentrocostosId { get; set; }

    [Column("centroscostosasociados_id")]
    public Guid? CentroscostosasociadosId { get; set; }

    [Column("conceptooaf_id")]
    public Guid? ConceptooafId { get; set; }

    [Column("unidadoperativa_id")]
    public Guid? UnidadoperativaId { get; set; }

    [Column("distribucionproveedores_id")]
    public Guid? DistribucionproveedoresId { get; set; }

    [Column("partidapresupventas_id")]
    public Guid? PartidapresupventasId { get; set; }

    [Column("itemsesquemaoperativo_id")]
    public Guid? ItemsesquemaoperativoId { get; set; }

    [Column("bocsf_id")]
    public Guid? BocsfId { get; set; }

    [Column("numerador_id")]
    public Guid? NumeradorId { get; set; }

    [Column("relacionimpproductoservicio_id")]
    public Guid? RelacionimpproductoservicioId { get; set; }

    [Column("condicion_id")]
    public Guid? CondicionId { get; set; }

    [Column("fechavencimientocondicion")]
    [StringLength(8)]
    public string Fechavencimientocondicion { get; set; }

    [Column("ultimamodificacion")]
    [StringLength(17)]
    public string Ultimamodificacion { get; set; }

    [Column("bo_place_id")]
    public Guid? BoPlaceId { get; set; }

    [Column("bo_owner_id")]
    public Guid? BoOwnerId { get; set; }

    [Column("unidadmedida_id")]
    public Guid? UnidadmedidaId { get; set; }

    [Column("unidadmedidanolineal_id")]
    public Guid? UnidadmedidanolinealId { get; set; }

    [Column("unidadesmedidaparticulares_id")]
    public Guid? UnidadesmedidaparticularesId { get; set; }

    [Column("unidminimcomer")]
    [Precision(22, 10)]
    public decimal? Unidminimcomer { get; set; }

    [Column("equivalenciasparticulares_id")]
    public Guid? EquivalenciasparticularesId { get; set; }

    [Column("unidadesdeexpresion_id")]
    public Guid? UnidadesdeexpresionId { get; set; }

    [Column("tipoextraccion_id")]
    public Guid? TipoextraccionId { get; set; }

    [Column("grupospertenecia_id")]
    public Guid? GruposperteneciaId { get; set; }

    [Column("datoscomplementarios_id")]
    public Guid? DatoscomplementariosId { get; set; }

    [Column("compania_id")]
    public Guid? CompaniaId { get; set; }

    [Column("atributosfusion_id")]
    public Guid? AtributosfusionId { get; set; }

    [Column("existenciaobligatoria")]
    public bool? Existenciaobligatoria { get; set; }

    [Column("unidadesporbulto")]
    [Precision(22, 10)]
    public decimal? Unidadesporbulto { get; set; }

    [Column("esmultiplodebultos")]
    public bool? Esmultiplodebultos { get; set; }

    [Column("configuradorimportacion_id")]
    public Guid? ConfiguradorimportacionId { get; set; }

    [Column("external_id")]
    [StringLength(10)]
    public string ExternalId { get; set; }

    [Column("utilizacantidadnolineal")]
    public bool? Utilizacantidadnolineal { get; set; }

    [Column("equivalenciasparticulnoli_id")]
    public Guid? EquivalenciasparticulnoliId { get; set; }

    [Column("unidadesmedidaparticulnoli_id")]
    public Guid? UnidadesmedidaparticulnoliId { get; set; }

    [Column("unidadesdeexpresionnoli_id")]
    public Guid? UnidadesdeexpresionnoliId { get; set; }

    [Column("proveedores_id")]
    public Guid? ProveedoresId { get; set; }

    [Column("existenciaobligatorianl")]
    public bool? Existenciaobligatorianl { get; set; }

    [Column("calculoexinolineal")]
    public bool? Calculoexinolineal { get; set; }

    [Column("tolerancia_id")]
    public Guid? ToleranciaId { get; set; }

    [Column("numeradoresserie_id")]
    public Guid? NumeradoresserieId { get; set; }

    [Column("explotaserieeninventario")]
    public bool? Explotaserieeninventario { get; set; }

    [Column("numeradoreslote_id")]
    public Guid? NumeradoresloteId { get; set; }

    [Column("numeradoresdespacho_id")]
    public Guid? NumeradoresdespachoId { get; set; }

    [Column("peso")]
    [Precision(22, 10)]
    public decimal? Peso { get; set; }

    [Column("volumen")]
    [Precision(22, 10)]
    public decimal? Volumen { get; set; }

    [Column("bienuso")]
    public bool? Bienuso { get; set; }

    [Column("stockminimo")]
    [Precision(22, 10)]
    public decimal? Stockminimo { get; set; }

    [Column("puntopedido")]
    [Precision(22, 10)]
    public decimal? Puntopedido { get; set; }

    [Column("stockseguridad")]
    [Precision(22, 10)]
    public decimal? Stockseguridad { get; set; }

    [Column("clientes_id")]
    public Guid? ClientesId { get; set; }

    [Column("descriptor_id")]
    public Guid? DescriptorId { get; set; }

    [Column("especificacionbase_id")]
    public Guid? EspecificacionbaseId { get; set; }

    [Column("especificaciones_id")]
    public Guid? EspecificacionesId { get; set; }

    [Column("explotapropiedades")]
    public bool? Explotapropiedades { get; set; }

    [Column("productossustitutos_id")]
    public Guid? ProductossustitutosId { get; set; }

    [Column("cantidad")]
    public int? Cantidad { get; set; }

    [Column("kit")]
    public bool? Kit { get; set; }

    [Column("stockmaximo")]
    [Precision(22, 10)]
    public decimal? Stockmaximo { get; set; }

    [Column("stockoptimo")]
    [Precision(22, 10)]
    public decimal? Stockoptimo { get; set; }

    [Column("alto")]
    [Precision(22, 10)]
    public decimal? Alto { get; set; }

    [Column("unidadmedidaalto_id")]
    public Guid? UnidadmedidaaltoId { get; set; }

    [Column("ancho")]
    [Precision(22, 10)]
    public decimal? Ancho { get; set; }

    [Column("unidadmedidaancho_id")]
    public Guid? UnidadmedidaanchoId { get; set; }

    [Column("espesor")]
    [Precision(22, 10)]
    public decimal? Espesor { get; set; }

    [Column("unidadmedidaespesor_id")]
    public Guid? UnidadmedidaespesorId { get; set; }

    [Column("unidadmedidavolumen_id")]
    public Guid? UnidadmedidavolumenId { get; set; }

    [Column("scriptpolinomicocosto_id")]
    public Guid? ScriptpolinomicocostoId { get; set; }

    [Column("envasepredeterminado_id")]
    public Guid? EnvasepredeterminadoId { get; set; }

    [Column("envasespermitidos_id")]
    public Guid? EnvasespermitidosId { get; set; }

    [Column("lineas_id")]
    public Guid? LineasId { get; set; }

    [Column("lineascodigos")]
    [StringLength(240)]
    public string Lineascodigos { get; set; }

    [Column("utilcnltotalitem")]
    public bool? Utilcnltotalitem { get; set; }

    [Column("dimensiones_id")]
    public Guid? DimensionesId { get; set; }

    [Column("tipoamortizacion_id")]
    public Guid? TipoamortizacionId { get; set; }

    [Column("porcentajereposicion")]
    [Precision(22, 10)]
    public decimal? Porcentajereposicion { get; set; }

    [Column("cuentascontables_id")]
    public Guid? CuentascontablesId { get; set; }

    [Column("cuentascontables2_id")]
    public Guid? Cuentascontables2Id { get; set; }

    [Column("cuentascontables3_id")]
    public Guid? Cuentascontables3Id { get; set; }

    [Column("cuentascontables4_id")]
    public Guid? Cuentascontables4Id { get; set; }

    [Column("cuentascontables5_id")]
    public Guid? Cuentascontables5Id { get; set; }

    [Column("cuentascontables6_id")]
    public Guid? Cuentascontables6Id { get; set; }

    [Column("cuentascontables7_id")]
    public Guid? Cuentascontables7Id { get; set; }

    [Column("cuentascontables8_id")]
    public Guid? Cuentascontables8Id { get; set; }

    [Column("cuentascontables9_id")]
    public Guid? Cuentascontables9Id { get; set; }

    [Column("cuentascontables10_id")]
    public Guid? Cuentascontables10Id { get; set; }

    [Column("svg")]
    public string Svg { get; set; }

    [Column("numeradorescodalt_id")]
    public Guid? NumeradorescodaltId { get; set; }

    [Column("creacioncodalt")]
    public bool? Creacioncodalt { get; set; }

    [Column("concatcodprod")]
    public bool? Concatcodprod { get; set; }

    [Column("categoria")]
    [StringLength(10)]
    public string Categoria { get; set; }

    [Column("cateant")]
    [StringLength(10)]
    public string Cateant { get; set; }

    [Column("montoproducto")]
    [Precision(22, 10)]
    public decimal? Montoproducto { get; set; }

    [Column("montototal")]
    [Precision(22, 10)]
    public decimal? Montototal { get; set; }

    [Column("porcentajecategoria")]
    [Precision(22, 10)]
    public decimal? Porcentajecategoria { get; set; }

    [Column("fechacategoria")]
    [StringLength(17)]
    public string Fechacategoria { get; set; }

    [Column("utilizaseriedetallada")]
    public bool? Utilizaseriedetallada { get; set; }
}