// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TransferenciasApiCore.Models;

[Table("unidadmedida")]
[Index("BoPlaceId", Name = "idx00343616")]
[Index("BoOwnerId", Name = "idx00343617")]
[Index("Simbolo", Name = "idx00343618")]
public partial class Unidadmedida
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("nombre")]
    [StringLength(40)]
    public string Nombre { get; set; }

    [Column("simbolo")]
    [StringLength(10)]
    public string Simbolo { get; set; }

    [Column("unidadminima")]
    [Precision(22, 10)]
    public decimal? Unidadminima { get; set; }

    [Column("redondeahaciaarribaapartir")]
    [Precision(22, 10)]
    public decimal? Redondeahaciaarribaapartir { get; set; }

    [Column("boextension_id")]
    public Guid? BoextensionId { get; set; }

    [Column("bo_place_id")]
    public Guid? BoPlaceId { get; set; }

    [Column("bo_owner_id")]
    public Guid? BoOwnerId { get; set; }

    [Column("activestatus")]
    public int? Activestatus { get; set; }
}