// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TransferenciasApiCore.Models.Transferencia;
public partial class EscoTxTransferenciaInsertDto
{
    public int? SolicitudTransferenciaId { get; set; }
    public int? EstadoId { get; set; }
    public Guid? DepositoOriId { get; set; }
    public Guid? DepositoDesId { get; set; }
    public int UsuarioId { get; set; }
    [NotMapped]
    public List<EscoTxItemTransferenciaInsertDto> ItemsTransferencia { get; set; }
}