// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TransferenciasApiCore.Models.Transferencia;

[Table("EscoTxItemTransferencia", Schema = "web")]
public partial class EscoTxItemTransferencia
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("producto_id")]
    public Guid? ProductoId { get; set; }

    [Column("cantidad")]
    public decimal? Cantidad { get; set; }

    [Column("unidadmedida_id")]
    public Guid? UnidadMedidaId { get; set; }

    [Column("transferencia_id")]
    public int? TransferenciaId { get; set; }

    [Column("estado_id")]
    public int? EstadoId { get; set; }
}