// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TransferenciasApiCore.Models.Transferencia;

[Table("EscoTxTransferencia", Schema = "web")]
public partial class EscoTxTransferencia
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("solicitudtransferencia_id")]
    public int? SolicitudTransferenciaId { get; set; }

    [Column("estado_id")]
    public int? EstadoId { get; set; }

    [Column("fecha", TypeName = "timestamp without time zone")]
    public DateTime? Fecha { get; set; }

    [Column("fechamodificacion", TypeName = "timestamp without time zone")]
    public DateTime? FechaModificacion { get; set; }

    [Column("procesadotransactor")]
    public bool? ProcesadoTransactor { get; set; }

    [Column("referencia_id", TypeName = "character varying")]
    public string ReferenciaId { get; set; }

    [Column("fechaprocesado", TypeName = "timestamp without time zone")]
    public DateTime? FechaProcesado { get; set; }

    [Column("depositoori_id")]
    public Guid? DepositoOriId { get; set; }

    [Column("depositodes_id")]
    public Guid? DepositoDesId { get; set; }

    [Column("usuario_id")]
    public int UsuarioId { get; set; }
    [NotMapped]
    public List<EscoTxItemTransferencia> ItemsTransferencia { get; set; }
}