// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace TransferenciasApiCore.Models.Transferencia;
public partial class EscoTxItemTransferenciaInsertDto
{
    public Guid? ProductoId { get; set; }
    public decimal? Cantidad { get; set; }
    public Guid? UnidadMedidaId { get; set; }
    [JsonIgnore]
    public int? TransferenciaId { get; set; }
    public int? EstadoId { get; set; }
}